config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'homepage#index'
  resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'favorite'
      post 'share'
    end
    collection do
      get 'search'
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get 'favorites'
    end
  end
  resources :cuisines, only: [:new, :create, :show]
  resources :food_types, only: [:new, :create, :show]
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  ENUM_LOCALE = 'activerecord.attributes.recipe.levels'
  enum level: [:easy, :moderate, :hard]
  belongs_to :food_type
  belongs_to :cuisine
  belongs_to :user

  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/recipes/missing_recipe_photo.jpg"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :name,
            :cuisine,
            :ingredients,
            :directions,
            presence: true

  def self.search_name word
    where("name LIKE ?", "%#{word}%")
  end

  def self.levels_i18n
    levels.keys.map { |key| [I18n.t("#{ENUM_LOCALE}.#{key}"), key] }
  end

  def level_i18n
    I18n.t("#{ENUM_LOCALE}.#{level}")
  end

  def self.recent_by_creation n=1
    order(:created_at).last(n)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :correct_user, only: [:destroy, :edit, :update]
  before_action :logged_in_user, only: [:create, :destroy, :update, :edit]
  before_action :set_collections, only:[:new, :edit]
  before_action :find_recipe, only:[:show, :edit, :destroy, :update]

  def new
    @recipe = Recipe.new
  end

  def search
    @recipes = Recipe.search_name params[:search]
  end

  def create
    @recipe = current_user.recipes.new recipe_params
    if @recipe.save
      flash[:success] = 'Criado com sucesso'
      redirect_to @recipe
    else
      flash.now[:errors] = @recipe.errors.full_messages
      set_collections
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @recipe.destroy
    flash[:success] = 'Sucesso'
    redirect_to root_path
  end

  def update
    if @recipe.update recipe_params
      flash.now[:success] = 'Sucesso'
      redirect_to @recipe
    else
      flash.now[:errors] = @recipe.errors.full_messages
      render 'edit'
    end
  end

  def favorite
    @recipe = Recipe.find params[:id]
    @favorite = @recipe.favorites.new user: current_user
    @favorite.save
    redirect_to @recipe
  end

  def share
    @recipe = Recipe.find params[:id]
    UserMailer.share_recipe_mail current_user, @recipe
    flash[:success] = 'Enviado com sucesso'
    redirect_to @recipe
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name,
                                     :photo,
                                     :cuisine_id,
                                     :food_type_id,
                                     :serving_ammount,
                                     :preparation_time,
                                     :level,
                                     :ingredients,
                                     :directions)
    end

    def find_recipe
      @recipe = Recipe.find params[:id]
    end

    def set_collections
      @food_types = FoodType.all
      @levels = Recipe.levels_i18n
      @cuisines = Cuisine.all
    end

    def correct_user
      @recipe = current_user.recipes.find_by(id: params[:id])
      flash[:danger] = 'Please Log in'
      redirect_to(root_url) if @recipe.nil?
    end
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :photo %>
  <%= f.file_field :photo, accept: 'image/png,image/jpeg'%>
  <%= f.label :cuisine_id %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>
  <%= f.label :food_type_id %>
  <%= f.collection_select :food_type_id, @food_types, :id, :name %>
  <%= f.label :serving_ammount %>
  <%= f.text_field :serving_ammount %>
  <%= f.label :preparation_time %>
  <%= f.text_field :preparation_time %>
  <%= f.label :level %>
  <%= f.select :level, @levels %>
  <%= f.label :ingredients %>
  <%= f.text_area :ingredients %>
  <%= f.label :directions %>
  <%= f.text_area :directions %>

  <%= f.submit %>
<% end %>

app/views/recipes/_recipe.html.erb
<%= recipe.user.name %>
<%= content_tag 'h2', recipe.name %>
<%= image_tag recipe.photo.url(:medium)%>
<%= recipe.cuisine.name %>
<%= recipe.food_type.name %>
<%= recipe.serving_ammount %>
<%= recipe.preparation_time %>
<%= recipe.level_i18n %>
<%= recipe.ingredients %>
<%= recipe.directions %>
<% if current_user == recipe.user %>
  <%= link_to 'Excluir', recipe, method: 'DELETE' %>
  <%= link_to 'Editar', edit_recipe_path(recipe) %>
<% end %>
<% if show_favorite_buttom?(recipe) %>
  <%= link_to 'Favoritar', favorite_recipe_path(recipe), method: 'POST' %>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/search.html.erb
Resultado
<% if @recipes.any? %>
  <%= render @recipes %>
<% else %>
  <%= 'Nada encontrado' %>
<% end %>

app/views/recipes/show.html.erb
<%= render @recipe %>

<% if logged_in? %>
  <div class="share">
    <%= form_tag share_recipe_path, method: 'POST' do %>
      <%= label_tag :email, 'Email' %>
      <%= text_field_tag :email %>
      <%= submit_tag 'Compartilhar', name: nil %>
    <% end %>
  </div>
<% end %>