config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'homepage#index'
  resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'favorite'
      post 'share'
    end
    collection do
      get 'search'
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get 'favorites'
    end
  end
  resources :cuisines, only: [:new, :create, :show]
  resources :food_types, only: [:new, :create, :show]
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end 
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save { self.mail = mail.downcase }

  has_many :recipes

  has_many :favorites
  has_many :favorited_recipes, through: :favorites, source: :recipe

  validates :password, presence: true, length: { minimum:6 }
  validates :mail, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  validates :mail, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: { maximum: 50 }
  validates :city, presence: true

  has_secure_password

  def already_favorited? recipe
    !!favorited_recipes.find_by(id: recipe.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only:[:update, :edit, :favorites]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = 'Criado com sucesso'
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render 'edit'
    end
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'Sucesso'
      log_in @user
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def favorites
    @recipes = @user.favorited_recipes
  end

  private
    def find_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:name, :mail, :city, :password,
                                   :password_confirmation, :facebook, :twitter)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = 'Please log in'
        redirect_to login_url
      end
    end

    def correct_user
      flash[:danger] = "You don't have permission"
      redirect_to(root_url) unless @user == current_user
    end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :mail, 'Email' %>
  <%= f.email_field :mail, class: 'form-control' %>
  <%= f.label :city, 'Cidade' %>
  <%= f.email_field :city, class: 'form-control' %>
  <%= f.label :facebook, 'Facebook' %>
  <%= f.text_field :facebook, class: 'form-control' %>
  <%= f.label :twitter, 'Twitter' %>
  <%= f.text_field :twitter, class: 'form-control' %>
  <%= f.label :password, 'Senha' %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation, 'Confirmação' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit text_submit, class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: { text_submit: 'Atualizar' } %>

app/views/users/favorites.html.erb
<%= render @recipes %>

app/views/users/new.html.erb
<%= render partial: 'form', locals: { text_submit: 'Registrar'} %>

app/views/users/show.html.erb
<%= content_tag :h2, @user.name %>
<%= @user.city %>
<%= @user.mail %>
<%= @user.facebook %>
<%= @user.twitter %>
<%= link_to 'Editar Perfil', edit_user_path(current_user) %>
<div class="recipes">
  <%= render @user.recipes %>
</div>
<%= link_to 'Favorites', favorites_user_path(@user) %>
<%= @user.favorites.count %>