config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'homepage#index'
  resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'favorite'
      post 'share'
    end
    collection do
      get 'search'
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get 'favorites'
    end
  end
  resources :cuisines, only: [:new, :create, :show]
  resources :food_types, only: [:new, :create, :show]
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialRecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <%= link_to "Social Recipes", root_path, class: 'navbar-brand' %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", '#' %></li>
              <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", '#' %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
      <%= form_tag search_recipes_path, method: 'get' do %>
        <%= label_tag :search, t('views.layout.search') %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag t('views.layout.search_submit'), name: nil %>
      <% end %>
      <% flash[:errors] && flash[:errors].each do |message| %>
        <%= content_tag :p, message %>
      <% end %>
      <%= content_tag :p, flash[:success] %>
      <%= content_tag :p, flash[:danger] %>
      <main>
        <%= yield %>
      </main>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>